### ISSUE TITLE
errors while cloning

### ISSUE THREAD

**Issue by limelect** [DeveloppeurPascal/_AllProjects#12]
While cloning huge amounts of errors with ide for window

**Comment by DeveloppeurPascal** [comment]
Hi

Depending on the folder path size git can't download some files.

In that case you can use git without the recursive mode to download the repository and after use commands 
git submodule init
git submodule update --remote

It should work better.

Just notice the subprojects won't have their sub modules. This repository can be used to backup or look at source codes of different projects. If you cant to test and compile one project, please go to its repository.

The games and utilities are available in a compiled version. Just ask if the download link in the README.md don't work.
