### ISSUE TITLE
Stll empty

### ISSUE THREAD

**Issue by limelect** [DeveloppeurPascal/_AllProjects#6]
Downloaded wit git still empty

**Comment by DeveloppeurPascal** [comment]
you can follow the steps explained here : 
https://www.theserverside.com/blog/Coffee-Talk-Java-News-Stories-and-Opinions/How-to-clone-a-git-repository-with-submodules-init-and-update

or if you are on Windows, you can use a software like https://gitforwindows.org which does the necessary by default
